### ISSUE TITLE
libzADC is underlinked, missing -ldl and -pthread

### ISSUE THREAD

**Issue by xnox** [ibm-genwqe/genwqe-user#81]
libzADC is underlinked, missing -ldl and -pthread

**Comment by fhaverkamp** [comment]
Hi xnox, did you find that by manual inspection, or did you use a tool to see that?
I guess:
[haverkam@oc7383187364 genwqe-user]$ objdump -p lib/libzADC.so | grep NEEDED
  NEEDED               libc.so.6
should actually include libdl and libpthread, since we use those in libzADC.so. Let me see how we can fix that.

[haverkam@oc7383187364 genwqe-user]$ ldd -r lib/libzADC.so
    linux-vdso.so.1 =>  (0x00007ffcf138b000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fd59347f000)
    /lib64/ld-linux-x86-64.so.2 (0x00000034ba400000)
undefined symbol: sem_init  (lib/libzADC.so)
undefined symbol: clock_gettime (lib/libzADC.so)
undefined symbol: dlsym (lib/libzADC.so)
undefined symbol: dlerror   (lib/libzADC.so)
undefined symbol: sem_timedwait (lib/libzADC.so)
undefined symbol: pthread_create    (lib/libzADC.so)
undefined symbol: pthread_cancel    (lib/libzADC.so)
undefined symbol: sem_post  (lib/libzADC.so)
undefined symbol: dlopen    (lib/libzADC.so)
undefined symbol: dlclose   (lib/libzADC.so)
undefined symbol: pthread_join  (lib/libzADC.so)

**Comment by fhaverkamp** [comment]
[haverkam@oc7383187364 genwqe-user]$ ldd -r lib/libzADC.so 
    linux-vdso.so.1 =>  (0x00007ffdc3d6b000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f24b4180000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f24b3f7c000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f24b3d73000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f24b39df000)
    /lib64/ld-linux-x86-64.so.2 (0x00000034ba400000)

I have added https://github.com/ibm-genwqe/genwqe-user/commit/7ee3f649c2cd95cf21e2d05561c6e9d96358a8b8 to solve this issue.

librt.so was missing too.

**Comment by fhaverkamp** [comment]
I think with those changes it should be fixed. Reopen if this is not correct. Thank you very much for pointing this out. I found that this was causing problems for our tryouts in the lab already. Now it should work better and simpler.
